name: On Tag Run

on:
  push
  # push:
  #   # Pattern matched against refs/tags
  #   tags:
  #     - "*" # Push events to every tag not containing /

env:
  DIR: multiplayer-ui

jobs:
  pushrelease:
    name: Push new release
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check-out multiplayer-ui repository
        uses: actions/checkout@v2
        with:
          repository: Bykow/factorio-mod-multiplayer-ui
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.DIR }}

      - name: Push release to portal
        run: python ${{ env.DIR }}/pushrelease.py
        shell: sh
        env:
          MOD_UPLOAD_API_KEY: ${{ secrets.MOD_UPLOAD_API_KEY }}
